// Autogenerated code by vite-plugin-svg-sprite-names-typescript
export type IconName = "globe" | "arrow-down" | "sun" | "moon" | "home" | "camera" | "book" | "user" | "folder";
export const IconNameList = ["globe", "arrow-down", "sun", "moon", "home", "camera", "book", "user", "folder"] as const;
